<?php

/**
 * @file
 * Contains migrate_ticketleap.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function migrate_ticketleap_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the migrate_ticketleap module.
    case 'help.page.migrate_ticketleap':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Migrate Ticketleap') . '</p>';
      return $output;

    default:
  }
}